name: flutter_clean_architecture
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  google_sign_in: ^5.0.7
  firebase_auth: ^3.0.2
  firebase_core: ^1.5.0
  cupertino_icons: ^1.0.2
  equatable: ^2.0.3
  uuid: ^3.0.6
  flow_builder: ^0.0.6
  flutter_bloc: ^8.0.1
  formz: ^0.4.1
  font_awesome_flutter: ^9.2.0
  dartz: ^0.10.1
  get_it: ^7.2.0
  mocktail: ^0.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0
  bloc_test: ^9.0.3

flutter:
  uses-material-design: true
  assets:
    - assets/
